### ISSUE TITLE
Missing Gamepad Mapping

### ISSUE THREAD

**Issue by MCPlayingTV** [minecraft-linux/linux-packaging-scripts#10]
The game is not openning when I have a mouse connected:

Missing Gamepad Mapping

Mapping for your gamepad. This Launcher has created an dummy Gamepad Mapping for you, you will have to create your own for best experience:

It was working before but stopped after few updates.

OS: elementaryOS
Source: Downloaded from AppCenter.

**Comment by ChristopherHX** [comment]
Sorry for the late reply, but this issue is fixed since 2021-01-04.
Please report further issues here: https://github.com/flathub/io.mrarm.mcpelauncher/issues instead
You are using the flatpak from flathub.
