### ISSUE TITLE
Wrong timestamps in GitHub... 

### ISSUE THREAD

**Issue by Hausemaster8281** [minecraft-linux/linux-packaging-scripts#11]
Just curious, but I have noticed that the last modified and the releases dates are not correct, as recently you have released ng images for arm devices, but the release date is at May 2020...

**Comment by ChristopherHX** [comment]
Just curious, but I have noticed that this issue is about my fork.

I may change that in the future, but don't have time for it.

**Comment by Hausemaster8281** [comment]
Oh, okay, well then I will close this issue, thanks for your reply!
