### ISSUE TITLE
Any way to use MC Education Edition APK file?

### ISSUE THREAD

**Issue by NoozAbooz** [minecraft-linux/linux-packaging-scripts#8]
Tried doing it but I got this error,
![image](https://user-images.githubusercontent.com/44128563/101975405-89385d00-3bf9-11eb-9933-b7287b082306.png)

**Comment by Hausemaster8281** [comment]
Firstly, I don't think this launcher supports education edition.(If you want to education edition, then just install a version of Minecraft bedrock and in the world creation options, activate cheats and toggle education edition).
Secondly, make sure that the architecture of your apk matches with that of your cpu, for example, if your cpu is x86 then the architecture of the apk also should be x86, if you don't own the game and you are on any other architecture than armhf, you might be out of luck, as most of the apk files on the internet are only arm compatible.
Thirdly, if it's a relatively new version of Minecraft, then, it takes time for the launcher to support them...

**Comment by MCMrARM** [comment]
pretty sure education edition is arm only

**Comment by NoozAbooz** [comment]
> pretty sure education edition is arm only

Oh sorry, forgot to mention I'm running a Raspberry Pi.

**Comment by ChristopherHX** [comment]
I don't have any apk of minecraft edu, but you have..

I'm not shure if the main lib is called `libminecraftedu.so`, but worth trying.
- Try renaming
`lib/armeabi-v7a/libminecraftedu.so` to `lib/armeabi-v7a/libminecraftpe.so` and / or `lib/arm64-v8a/libminecraftedu.so` to `lib/arm64-v8a/libminecraftpe.so` inside the apk file (it's just a zip file)

- Then import again.
- It may crash now instead, I doubt that it will work

About failed to stat selected file: **make shure the apk is copied to your device's sd card not via mtp or other storage provider.**

**Comment by NoozAbooz** [comment]
> I don't have any apk of minecraft edu, but you have..
> 
> I'm not shure if the main lib is called `libminecraftedu.so`, but worth trying.
> 
> * Try renaming
>   `lib/armeabi-v7a/libminecraftedu.so` to `lib/armeabi-v7a/libminecraftpe.so` and / or `lib/arm64-v8a/libminecraftedu.so` to `lib/arm64-v8a/libminecraftpe.so` inside the apk file (it's just a zip file)
> * Then import again.
> * It may crash now instead, I doubt that it will work
> 
> About failed to stat selected file: **make shure the apk is copied to your device's sd card not via mtp or other storage provider.**

Seems like there isn't a lib folder in the apk file: 
![image](https://user-images.githubusercontent.com/44128563/108872118-15321200-75b7-11eb-803c-17bd60dfc636.png)

MC Edu edition is free so you can find a few apks scattered around the web.

**Comment by ChristopherHX** [comment]
There is no lib in assets.
lib is a folder next to assets.

so `assets/../lib`

Also if you have multiple apks just choose the one witg the lib folder in the root

**Comment by NoozAbooz** [comment]
> There is no lib in assets.
> lib is a folder next to assets.
> 
> so `assets/../lib`

Well uh 
![image](https://user-images.githubusercontent.com/44128563/108872876-e0728a80-75b7-11eb-8e74-bc669d70646d.png)

**Comment by ChristopherHX** [comment]
You need more apks than the base apk like the arm configuration apk.

Otherwise it is a incomplete set of apks

**Comment by NoozAbooz** [comment]
So something like this?
![image](https://user-images.githubusercontent.com/44128563/108873586-82927280-75b8-11eb-8665-e20ce49ebad4.png)

**Comment by NoozAbooz** [comment]
The problem is my RPI is running a 32-bit OS...

**Comment by ChristopherHX** [comment]
Then you additionally need `config.armeabi-v7a.apk` if it exists.
Or reinstall arm64 os if you have a rpi3 or newer

**Comment by NoozAbooz** [comment]
Hm... I'll go search around and see if I can find a arm32 one.

**Comment by NoozAbooz** [comment]
> Then you additionally need `config.armeabi-v7a.apk` if it exists.
> Or reinstall arm64 os if you have a rpi3 or newer

Say I got a arm32 bit apk, what do I do with it? Do I just copy the lib folder inside it to the base apk?

**Comment by ChristopherHX** [comment]
1. open `config.armeabi-v7a.apk`
2. rename the `libminecraft*.so` in `lib/armeabi-v7a/` to `libminecraftpe.so` if it has a different name
3. save `config.armeabi-v7a.apk` (use the old zip format or the launcher won't accept it)
4. select **all** apks `com.mojang.minecraftedu.apk`, `config.*.apk` in the import dialog or it won't accept it at all

I don't believe minecraftedu has an armv7 version
- arm chromebooks are usually arm64
- minecraftedu for chromebooks was released after 64 bit android versions of minecraft are common
- Minecraftpe on android may discontinue the 32bit version soon [Our ability to support Android devices on KitKat OS or below is coming to an end](https://feedback.minecraft.net/hc/en-us/articles/360057279331-Minecraft-Beta-1-16-210-60-Xbox-One-Windows-10-Android-), kitkat the last 32bit only android
- playstore will stops delivering 32bit native apps to android 9 64bit or higher
